# Generated by Django 3.0.6 on 2020-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diplome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='compagnies',
            field=models.CharField(max_length=50),
        ),
    ]
